### ISSUE TITLE
Add command cooldowns

### ISSUE THREAD

**Issue by c-eg** [c-eg/Rocket-League-Private-Matches-Discord-Bot#33]
Add command cooldowns to any command that access the database.

checkpeak, setpeak, queue

**Comment by ShubhamNagure** [comment]
I'd like to work on it, please assign me !

**Comment by c-eg** [comment]
Sure, thanks!

**Comment by ShubhamNagure** [comment]
Hi @c-eg ,

I see a problem while installing dependencies. PSB.
`ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 25), async-timeout==4.0.1 and multidict==5.2.0 because these package versions have conflicting dependencies.`

Let me know the exact python version for dev-env setup.

best regards,
Shubham

**Comment by c-eg** [comment]
Ah I see, try using Python 3.10 and see if you get the same issue

**Comment by ShubhamNagure** [comment]
still no luck.
`ERROR: Cannot install -r requirements.txt (line 10) and aiohttp==3.8.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested aiohttp==3.8.1
    discord-py 1.7.3 depends on aiohttp<3.8.0 and >=3.6.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies`

I tried these python versions 3.6.9, 3,9, 3.10.

let me know the correct python version to install dependencies.

**Comment by c-eg** [comment]
Ahh okay thanks for trying, I’ll fix at some point today. I’ll make a new issue for it :)

**Comment by c-eg** [comment]
It should be fixed now from #38

**Comment by ShubhamNagure** [comment]
yup it's working, for portability created a docker container.

**Comment by c-eg** [comment]
Perfect!

**Comment by ShubhamNagure** [comment]
Done!
let me know if you want the container, I'll open a separate PR.

**Comment by c-eg** [comment]
If you make a separate PR, I can look into docker and merge if wanted

**Comment by c-eg** [comment]
closed in #39
